export const ADD_VALUE = 'ADD_VALUE'
export const DELETE_VALUE = 'DELETE_VALUE'
export const CLEAR = 'CLEAR'
export const EVALUATE = 'EVALUATE'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'
export const SHOW_HISTORY = 'SHOW_HISTORY'
export const THEME_TOGGLE = 'THEME_TOGGLE'
export const SET_ERROR = 'SET_ERROR'
